baseURL = 'https://alterego.berlime.com'
languageCode = 'en-us'
title = 'Alter Ego 2'
theme = 'gokarna'

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='book'></span>"

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
    pre = "<span data-feather='tag'></span>"

[[menu.main]]
    identifier = 'github'
    url = "https://github.com/Berlime/hugo"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
    identifier = "coffee"
    url = "https://www.buymeacoffee.com/"
    weight = 4
    # Without using feather-icons
    pre = "<span data-feather='coffee'></span>" 

    [params]
  # URL for the avatar on homepage
  avatarURL = "/images/avatar/gokarna.jpg"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-m"

  # Description to display on homepage
  socialIcons = [
    {name = "facebook", url = "https://www.facebook.com/Berlime5"},
    {name = "instagram", url = "https://www.instagram.com/Berlime"},
    {name = "linkedin", url = "https://www.linkedin.com/in/berlime-solutions/"},
    {name = "email", url = "mailto:kamel@berlime.com"},
    {name = "x", url = "https://x.com/berlime"}
  ]

  description = "A continuation from https://berlime5.blogspot.com"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # Display "back to top" button on posts
  ShowBackToTopButton = true

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = "recent"

  # Footer text
  footer = "The Marauders"